/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppAdminAdminsRouteImport } from './routes/_app/_admin/admins'
import { Route as AppAdminPayslipsRouteImport } from './routes/_app/_admin/payslips'
import { Route as AppAdminProjectsRouteImport } from './routes/_app/_admin/projects'
import { Route as AppAdminStaffRouteImport } from './routes/_app/_admin/staff'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAdminsRoute = AppAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPayslipsRoute = AppAdminPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProjectsRoute = AppAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStaffRoute = AppAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/me': typeof AppMeRoute
  '/admins': typeof AppAdminAdminsRoute
  '/payslips': typeof AppAdminPayslipsRoute
  '/projects': typeof AppAdminProjectsRoute
  '/staff': typeof AppAdminStaffRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/me': typeof AppMeRoute
  '/admins': typeof AppAdminAdminsRoute
  '/payslips': typeof AppAdminPayslipsRoute
  '/projects': typeof AppAdminProjectsRoute
  '/staff': typeof AppAdminStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/me': typeof AppMeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_admin/admins': typeof AppAdminAdminsRoute
  '/_app/_admin/payslips': typeof AppAdminPayslipsRoute
  '/_app/_admin/projects': typeof AppAdminProjectsRoute
  '/_app/_admin/staff': typeof AppAdminStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/me' | '/admins' | '/payslips' | '/projects' | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/me' | '/admins' | '/payslips' | '/projects' | '/staff'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_admin'
    | '/_app/me'
    | '/_app/'
    | '/_app/_admin/admins'
    | '/_app/_admin/payslips'
    | '/_app/_admin/projects'
    | '/_app/_admin/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_admin/admins': {
      id: '/_app/_admin/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AppAdminAdminsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/payslips': {
      id: '/_app/_admin/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AppAdminPayslipsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/projects': {
      id: '/_app/_admin/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppAdminProjectsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/staff': {
      id: '/_app/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppAdminStaffRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAdminsRoute: typeof AppAdminAdminsRoute
  AppAdminPayslipsRoute: typeof AppAdminPayslipsRoute
  AppAdminProjectsRoute: typeof AppAdminProjectsRoute
  AppAdminStaffRoute: typeof AppAdminStaffRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAdminsRoute: AppAdminAdminsRoute,
  AppAdminPayslipsRoute: AppAdminPayslipsRoute,
  AppAdminProjectsRoute: AppAdminProjectsRoute,
  AppAdminStaffRoute: AppAdminStaffRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppMeRoute: typeof AppMeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppMeRoute: AppMeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
