// utilities.css から node scripts/styles.ts --gen で生成する。手で書き換えない
// クラス名と、そのクラスが書き換えるプロパティ
export const utilities = {
  "flex": ["display"],
  "grid": ["display"],
  "wrap": ["flex-wrap"],
  "items-center": ["align-items"],
  "items-end": ["align-items"],
  "grid-fit": ["grid-template-columns"],
  "gap-1": ["row-gap", "column-gap"],
  "gap-3": ["row-gap", "column-gap"],
  "gap-4": ["row-gap", "column-gap"],
  "max-w-page": ["max-width"],
  "m-x-auto": ["margin-left", "margin-right"],
  "m-r-auto": ["margin-right"],
  "p-5": ["padding-top", "padding-right", "padding-bottom", "padding-left"],
  "p-x-4": ["padding-left", "padding-right"],
  "p-x-5": ["padding-left", "padding-right"],
  "p-x-6": ["padding-left", "padding-right"],
  "p-y-2": ["padding-top", "padding-bottom"],
  "p-y-3": ["padding-top", "padding-bottom"],
  "p-y-5": ["padding-top", "padding-bottom"],
  "m-t-0": ["margin-top"],
  "m-b-4": ["margin-bottom"],
  "m-y-3": ["margin-top", "margin-bottom"],
  "m-y-5": ["margin-top", "margin-bottom"],
  "border": ["border-top", "border-right", "border-bottom", "border-left"],
  "border-accent": ["border-top", "border-right", "border-bottom", "border-left"],
  "border-current": ["border-top", "border-right", "border-bottom", "border-left"],
  "radius-1": ["border-radius"],
  "radius-2": ["border-radius"],
  "bg-surface": ["background"],
  "bg-accent": ["background"],
  "bg-accent-tint": ["background"],
  "bg-transparent": ["background"],
  "fg-muted": ["color"],
  "fg-accent": ["color"],
  "fg-on-accent": ["color"],
  "fg-error": ["color"],
  "fg-success": ["color"],
  "fs-title": ["font-size"],
  "text-right": ["text-align"],
  "tabular-nums": ["font-variant-numeric"],
} as const;

export type Utility = keyof typeof utilities;
